### ISSUE TITLE
As a user, I can run HTM over HTTP

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/hitc#10]
Given that I have model params and appropriate data, an HTTP user should be able to:

---
- [x] [Create a model](https://github.com/nupic-community/htm-over-http/issues/5)
- [x] [Push data to a model](https://github.com/nupic-community/htm-over-http/issues/9)
- [x] [Delete a model](https://github.com/nupic-community/htm-over-http/issues/8)

**Comment by fergalbyrne** [comment]
You should also have a getter for model/timestep, possibly model/timestep/spec-of-what-i-want

**Comment by rhyolight** [comment]
@fergalbyrne Eventually I think that would be cool, but I'm not quite ready to spec that out yet.
