### ISSUE TITLE
REST API cannot assume the temporal field name is "timestamp"

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/hitc#22]
When running data through a model during a PUT, the request handler makes an assumption that the temporal data stream is named `timestamp`, but this is not always the case. During the creation of a model, any temporal timestamps can be found by inspecting the model parameters. This should be stored in memory for future requests and used when handling input data.

**Comment by JonnoFTW** [comment]
You haven't done safety checks, if there is no temporal field, then the variable will be none and the places it's been used will fail.

See my commit for how I did it:
https://github.com/JonnoFTW/htm-over-http/commit/f8c75c643dfb954fbd553931586971aa455c7e6c

**Comment by rhyolight** [comment]
I see now. I'll get around to this...
