### ISSUE TITLE
Create a Python API client

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/hitc#27]
Should have complete functionality of the API. Repo is https://github.com/nupic-community/hitc-py. Should be `pip`-installable.

**Comment by rhyolight** [comment]
[Here is what I am using now](https://github.com/rhyolight/smartthings.htm.bridge/blob/master/htmclient.py).

**Comment by JonnoFTW** [comment]
I started a client. I'll fork that repo and move the code over.

https://github.com/JonnoFTW/htm-over-http/blob/master/test/hitc.py

**Comment by JonnoFTW** [comment]
Project has been created here: 

https://github.com/nupic-community/hitc-py
