### ISSUE TITLE
What cloud service will be our deployment target?

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/hitc#4]
Depends on #2 to some extent. I am biased towards [Heroku](http://heroku.com) because I've used it a lot and it is pretty simple to deploy and control from a local command line. 

Options are (feel free to add more):
- Heroku
- Google App Engine

**Comment by jefffohl** [comment]
+1 to Heroku. I have had good experiences with that service.

**Comment by JonnoFTW** [comment]
I've never used a cloud deployment service, but heroku looks workable. If others are fine with that that's all good. As long as it supports our requirements that should be good.

**Comment by rhyolight** [comment]
Heroku it is.
