### ISSUE TITLE
As an HTTP client, I can create an HTM model in a RESTful way

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/hitc#5]
Very simple endpoints:
- **POST** `/models`: create model 
  - _body_ [JSON] [example](https://gist.github.com/rhyolight/20c937c15e5ae3333f89):
    - `modelParams`: same structure as the NuPIC / HTM.Java model params (sorry, we have no real spec for this, you'll just have to look at some example code)
    - `predictedField` [optional]: the string name of the field to be predicted (not necessary for anomaly models)
  - _returns_ [JSON]: model id to identify the model instance for future calls (`{"id":"asdf"}`)

Errors should return a non 200 status code representing the error as well as possible.

**Comment by rhyolight** [comment]
I updated the URLs in the description spec above to be more RESTful.

**Comment by fergalbyrne** [comment]
Suggestion: There's an underlying default model spec (use Grok), so passing an empty JSON map gives you that. The JSON you give just overrides this map (using a merge).

**Comment by rhyolight** [comment]
@fergalbyrne Yes, great idea. I will put that in another ticket.

**Comment by JonnoFTW** [comment]
Does the api need to include the predicted field? Currently it's in the URL as `/create/{predicted_field}`. Doesn't seem very RESTy though.

**Comment by rhyolight** [comment]
~~No, the predicted field is within the model params.~~ (I was wrong, see example model params in next comment)

**Comment by rhyolight** [comment]
Example **POST** payload here: https://gist.github.com/rhyolight/20c937c15e5ae3333f89
