### ISSUE TITLE
As an HTTP client, I can push data to an HTM model in a RESTful way

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/hitc#9]
- **PUT** `/models/<id>`: push data to model identified by `<id>`
  - _body_ [JSON]: data to push to model instance
  - _returns_ [JSON]: response object with same structure as the NuPIC OPF [ModelResponse](https://github.com/numenta/nupic/blob/master/src/nupic/frameworks/opf/opfutils.py#L280-L343) object.

If model does not exist, return 404. Success should return 200. Errors should return non-200 response status codes.

Depends on #5.

**Comment by fergalbyrne** [comment]
Should also return an error if overwriting a timestep which has been already processed. Specify such semantic errors in this thread.

**Comment by rhyolight** [comment]
@fergalbyrne See #12.

**Comment by rhyolight** [comment]
@JonnoFTW I'm thinking maybe the POST body for this one containing the data should just be a CSV string instead of JSON. Would be simpler and lighter. What do you think?

**Comment by JonnoFTW** [comment]
JSON makes sure that you don't get the field order messed up. The model doesn't know what order the fields are going to appear in and this will complicate making a model, so I'd probably suggest sticking with JSON, unless you want to encode them form data.

**Comment by rhyolight** [comment]
:+1:
